name: Ingestion Data Factory

pr:
  autoCancel: false

trigger:
  branches:
    include:
      - main
    exclude:
      - /**/*.md

stages:
- ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual')) }}:
  - template: azure_devops/templates/build-stage.yaml
    parameters:
      name: Build
      service_connection: scn-sub-cdp-preprd-we-001
      env_path: cdp-preprd
      env: dev
      instance_name: ojsu

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
  - template: azure_devops/templates/release-stage.yaml
    parameters:
      name: CDPPreProd
      env_path: cdp-preprd
      env: dev      
      instance_name: ojsu
      service_connection: scn-sub-cdp-preprd-we-001
      depends_on: Build
      shared_ir_resource_id: /subscriptions/d12cd7ca-ec96-4566-8890-89f3194d1169/resourceGroups/rg-ingestion-cdp-preprd-we-ojsu/providers/Microsoft.DataFactory/factories/adf-ingestion-cdp-preprd-we-ojsu/integrationruntimes/dev

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
  - template: azure_devops/templates/release-stage.yaml
    parameters:
      name: CDPPreProd
      env_path: cdp-preprd
      env: tst      
      instance_name: ojsu
      service_connection: scn-sub-cdp-preprd-we-001
      depends_on: Deploy_CDPPreProd_dev
      shared_ir_resource_id: /subscriptions/d12cd7ca-ec96-4566-8890-89f3194d1169/resourcegroups/rg-ingestion-cdp-preprd-we-ojsu/providers/Microsoft.DataFactory/factories/adf-ingestion-cdp-preprd-we-ojsu/integrationruntimes/tst

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
  - template: azure_devops/templates/release-stage.yaml
    parameters:
      name: CDPPreProd
      env_path: cdp-preprd
      env: acp      
      instance_name: ojsu
      service_connection: scn-sub-cdp-preprd-we-001
      depends_on: Deploy_CDPPreProd_tst
      shared_ir_resource_id: /subscriptions/d12cd7ca-ec96-4566-8890-89f3194d1169/resourcegroups/rg-ingestion-cdp-preprd-we-ojsu/providers/Microsoft.DataFactory/factories/adf-ingestion-cdp-preprd-we-ojsu/integrationruntimes/acp
