resources:
  repositories: 
    - repository: templateRepo
      type: git
      name: Data Platform/azure-devops-templates
      ref: refs/heads/main

name: terraform

pool:
  vmImage: 'ubuntu-latest'

trigger:
  tags:
    include:
    - '*'

variables:
  - name: dbx_cli_version
    value: '0.230.0'

stages:
- template: azure_devops/templates/build-stage.yaml
  parameters:
    name: Build
    service_connection: scn-sub-cdp-preprd-we-001
    env_path: cdp-preprd
    env: dev
    instance_name: ojsu
# csf:3.3.11a:Manual approval to release to Production
- template: templates/approval-stage.yaml@templateRepo
  parameters:
    name: approve_release_to_production
    dependsOn: Build
    approval_environment: production-approvers-infra
# only release from tag, or a manual run which disables apply
- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
  - template: azure_devops/templates/release-stage.yaml
    parameters:
      name: CDPProd
      env_path: cdp-prd
      env: prd      
      instance_name: kutk
      service_connection: scn-cdp-prd-we-001
      dependsOn: approve_release_to_production
      shared_ir_resource_id: /subscriptions/50c97cee-4d5e-44b3-ba85-6b12b2634abe/resourcegroups/rg-ingestion-cdp-prd-we-kutk/providers/Microsoft.DataFactory/factories/adf-ingestion-cdp-prd-we-kutk/integrationruntimes/prd
  
  - template: templates/stages/deploy-databricks-asset-bundle.yaml@templateRepo
    parameters:
      stage_name: DeployDatabricksAssetBundle_acp
      dependsOn: approve_release_to_production
      agent_pool_name: cdp-runners-prd
      service_connection: scn-sub-cdp-preprd-we-001
      dbx_env: acp
      dbx_cli_version: $(dbx_cli_version)
      skip_apply: false
